#!/bin/python3

import math
#https://www.hackerrank.com/challenges/one-week-preparation-kit-time-conversion/problem?isFullScreen=true&h_l=interview&playlist_slugs%5B%5D=preparation-kits&playlist_slugs%5B%5D=one-week-preparation-kit&playlist_slugs%5B%5D=one-week-day-one

import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    # Code modified by marianelavflora           
    hour = int(s[0:2])
    minutesSeconds = s[2: 8]
    
    if "AM" in s and hour == 12:
        hour = hour
        hour = "00"
    elif "PM" in s and hour != 12:    
        hour = hour + 12       
    
    return f"{hour:02}{minutesSeconds}"
    
    
    #end of modified code by marianelavflora 
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
